version: '2'
services:
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./nginx-01:/etc/nginx
      - ./log:/log
    ports:
      - "443:443"
    links:
      - isucoin

  isucoin:
    environment:
      ISU_APP_PORT:    '5000'
      ISU_DB_HOST:     '172.16.15.2'
      ISU_DB_PORT:     '13306'
      ISU_DB_USER:     'isucon'
      ISU_DB_PASSWORD: 'isucon'
      ISU_DB_NAME:     'isucoin'
      ISU_PUBLIC_DIR:  '/public'
    volumes:
      - ./public:/public
    ports:
      - "5000:5000"
